// Type declarations for @google/model-viewer web component
declare namespace JSX {
  interface IntrinsicElements {
    'model-viewer': {
      src?: string;
      alt?: string;
      'camera-controls'?: boolean | string;
      'auto-rotate'?: boolean | string;
      'interaction-policy'?: string;
      'ar'?: boolean | string;
      'ar-scale'?: string;
      'ar-modes'?: string;
      'ios-src'?: string;
      'poster'?: string;
      'environment-image'?: string;
      'exposure'?: string;
      'shadow-intensity'?: string;
      'shadow-softness'?: string;
      'animation-name'?: string;
      'animation-crossfade-duration'?: string;
      'autoplay'?: boolean | string;
      'background-color'?: string;
      'camera-orbit'?: string;
      'camera-target'?: string;
      'field-of-view'?: string;
      'min-camera-orbit'?: string;
      'max-camera-orbit'?: string;
      'min-field-of-view'?: string;
      'max-field-of-view'?: string;
      'interpolation-decay'?: string;
      'skybox-image'?: string;
      'environment-image'?: string;
      'reveal'?: string;
      'loading'?: string;
      'with-credentials'?: boolean | string;
      'touch-action'?: string;
      'disable-zoom'?: boolean | string;
      'orbit-sensitivity'?: string;
      'interaction-prompt'?: string;
      'interaction-prompt-threshold'?: string;
      'interaction-prompt-style'?: string;
      'camera-controls'?: boolean | string;
      'auto-rotate'?: boolean | string;
      'auto-rotate-delay'?: string;
      'rotation-per-second'?: string;
      'disable-tap'?: boolean | string;
      'magic-leap'?: boolean | string;
      'ar'?: boolean | string;
      'ar-scale'?: string;
      'ar-modes'?: string;
      'ar-placement'?: string;
      'ar-interaction'?: string;
      'xr-environment'?: boolean | string;
      'poster'?: string;
      'reveal'?: string;
      'loading'?: string;
      'with-credentials'?: boolean | string;
      'skybox-height'?: string;
      'shadow-intensity'?: string;
      'shadow-softness'?: string;
      'environment-image'?: string;
      'exposure'?: string;
      'tone-mapping'?: string;
      'color-space'?: string;
      'decoding'?: string;
      'preload'?: boolean | string;
      'interpolation'?: string;
      'interpolation-decay'?: string;
      'animation-name'?: string;
      'animation-crossfade-duration'?: string;
      'variant-name'?: string;
      'orientation'?: string;
      'scale'?: string;
      'bounds'?: string;
      'min-scale'?: string;
      'max-scale'?: string;
      'interaction-policy'?: string;
      'interaction-prompt'?: string;
      'interaction-prompt-threshold'?: string;
      'interaction-prompt-style'?: string;
      'camera-orbit'?: string;
      'camera-target'?: string;
      'field-of-view'?: string;
      'min-camera-orbit'?: string;
      'max-camera-orbit'?: string;
      'min-field-of-view'?: string;
      'max-field-of-view'?: string;
      'disable-zoom'?: boolean | string;
      'orbit-sensitivity'?: string;
      'touch-action'?: string;
      'disable-tap'?: boolean | string;
      'magic-leap'?: boolean | string;
      'xr-environment'?: boolean | string;
      style?: React.CSSProperties;
      className?: string;
      id?: string;
      children?: React.ReactNode;
      onLoad?: (event: Event) => void;
      onError?: (event: ErrorEvent) => void;
      onProgress?: (event: Event) => void;
      onModelLoad?: (event: Event) => void;
      onCameraChange?: (event: Event) => void;
      onEnvironmentChange?: (event: Event) => void;
      onVariantChange?: (event: Event) => void;
      onPosterDismiss?: (event: Event) => void;
      onReveal?: (event: Event) => void;
      onInteractionPrompt?: (event: Event) => void;
      onInteractionPromptDismiss?: (event: Event) => void;
      onInteractionPromptProgress?: (event: Event) => void;
      onInteractionPromptPointer?: (event: Event) => void;
      onInteractionPromptVisibilityChange?: (event: Event) => void;
      onInteractionPromptStyleChange?: (event: Event) => void;
      onCameraOrbitChange?: (event: Event) => void;
      onCameraTargetChange?: (event: Event) => void;
      onFieldOfViewChange?: (event: Event) => void;
      onScaleChange?: (event: Event) => void;
      onOrientationChange?: (event: Event) => void;
      onBoundsChange?: (event: Event) => void;
      onVariantNameChange?: (event: Event) => void;
      onAnimationNameChange?: (event: Event) => void;
      onPosterDismissed?: (event: Event) => void;
      onRevealed?: (event: Event) => void;
      onModelLoaded?: (event: Event) => void;
      onEnvironmentLoaded?: (event: Event) => void;
      onSkyboxLoaded?: (event: Event) => void;
      onPosterLoaded?: (event: Event) => void;
      onPosterDismissed?: (event: Event) => void;
      onRevealed?: (event: Event) => void;
      onModelLoaded?: (event: Event) => void;
      onEnvironmentLoaded?: (event: Event) => void;
      onSkyboxLoaded?: (event: Event) => void;
      onPosterLoaded?: (event: Event) => void;
    };
  }
}

